[package]
name = "simulation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oorandom = "11"
jemallocator = { version = "0.3", optional = true }

[workspace]
