[package]
name = "common"
version = "0.4.0"
authors = ["Jan Bujak <jan.bujak@nokia.com>"]
edition = "2018"

[dependencies]
lz4-compress = { path = "../lz4-compress" }
speedy = "0.4"
speedy-derive = "0.3"
byteorder = "1"
libc = "0.2"
